---
- name: Installing tmux
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Creating bash directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ bash_user_name }}"
    group: "{{ bash_user_group }}"
  loop:
    - "{{ bash_scripts_dir }}"
    - "{{ bash_custom_scripts_dir }}"

- name: Creating bash files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bash_scripts_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ bash_user_name }}"
    group: "{{ bash_user_group }}"
  loop:
    - 01-git-prompt.sh
    - "{{ bash_ps1_file }}"
    - 03-greeting.sh
    - 04-work-aliases.sh
    - 05-golang.sh
    - 06-tmux.sh
  loop_control:
    label: "{{ bash_scripts_dir }}/{{ item }}"

- name: Creating .bash_aliases file
  ansible.builtin.template:
    src: bash/bash_aliases.sh.j2
    dest: "{{ bash_user_home }}/.bash_aliases"
    mode: "0644"
    owner: "{{ bash_user_name }}"
    group: "{{ bash_user_group }}"
