---
- name: Creating rofi configuration directory
  tags: rofi
  ansible.builtin.file:
    path: "{{ i3_rofi_config_file | dirname }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Creating rofi configuration file
  tags: cfg,rofi
  ansible.builtin.template:
    src: "rofi/config.rasi.j2"
    dest: "{{ i3_rofi_config_file }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Creating rofi theme file
  tags: cfg,rofi
  ansible.builtin.template:
    src: "rofi/theme.rasi.j2"
    dest: "{{ i3_rofi_config_file | dirname }}/theme.rasi"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
