---
# Can't do it with normal repositories because Mr.Mint is oldie but goldie.
# - name: Installing updated i3 .deb package
#   tags: apt, i3_apt
#   ansible.builtin.apt:
#     deb: "{{ item }}"
#   loop:
#     - "{{ i3_deb_url }}"
#     - "{{ i3_wm_deb_url }}"

- name: Installing i3
  tags: apt, i3_apt
  ansible.builtin.apt:
    name:
      - i3
      - i3-wm

- name: Installing i3 complement apps
  tags: apt
  ansible.builtin.apt:
    name:
      - rofi
      - numlockx
      - scrot
      - imagemagick
      - xautolock
    state: present
    cache_valid_time: 3600
    update_cache: true
    autoremove: true
    autoclean: true

- name: Creating custom scripts dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - "{{ i3_config_dir }}"
    - "{{ i3_status_dir }}"

- name: Creating i3 configuration file
  tags: cfg, i3cfg
  ansible.builtin.template:
    src: "i3/config.cfg.j2"
    dest: "{{ i3_config_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - config
  loop_control:
    label: "{{ i3_config_dir }}/{{ item }}"
  notify: Restart i3

- name: Creating x11 configuration files
  tags: cfg, i3cfg, x11
  ansible.builtin.template:
    src: x11/{{ item }}.j2
    dest: /etc/X11/xorg.conf.d/{{ item }}
    mode: "0644"
  loop:
    - 50-mouse-acceleration.conf
    - 50-no-power-management.conf
  loop_control:
    label: /etc/X11/xorg.conf.d/{{ item }}
  notify: Restart i3

- name: Creating i3status configuration file
  tags: cfg, i3statuscfg
  ansible.builtin.template:
    src: "i3status/config.cfg.j2"
    dest: "{{ i3_status_dir }}/{{ item }}"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - config
  loop_control:
    label: "{{ i3_config_dir }}/{{ item }}"
  notify: Restart i3

- name: Creating gtk configuration files
  tags: cfg,gtk
  ansible.builtin.template:
    src: "{{ item.gtk_version }}/{{ item.gtk_file }}.j2"
    dest: "{{ common_user_config_dir }}/{{ item.gtk_version }}/{{ item.gtk_file }}"
    mode: "0664"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
  loop:
    - gtk_file: settings.ini
      gtk_version: gtk-3.0
  loop_control:
    label: "{{ common_user_config_dir }}/{{ item.gtk_version }}/{{ item.gtk_file }}"
  notify: Restart i3

- name: Importing tasks
  ansible.builtin.import_tasks: rofi.yml
