---
- name: Installing lightdm
  tags: tasks_display_manager
  ansible.builtin.apt:
    name: lightdm
    state: present

- name: Creating slick-greeter config
  tags: tasks_display_manager
  ansible.builtin.template:
    dest: /etc/lightdm/slick-greeter.conf
    src: slick-greeter.conf.j2
    force: true
    mode: "0644"
    owner: root
    group: root
