---

- name: Downloading zellij tar.gz
  ansible.builtin.get_url:
    url: https://github.com/zellij-org/zellij/releases/download/v0.43.0/zellij-x86_64-unknown-linux-musl.tar.gz
    dest: "/tmp/zellij.tar.gz"

- name: Unarchive zellij
  ansible.builtin.unarchive:
    src: "/tmp/zellij.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Creating zellij binary
  ansible.builtin.copy:
    src: "/tmp/zellij"
    dest: "{{ common_user_home }}/.local/bin/zellij"
    remote_src: true
    mode: "0755"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Create zellij config directory
  ansible.builtin.file:
    path: "{{ common_user_config_dir }}/zellij"
    mode: "0755"
    state: directory
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"

- name: Create zellij config file
  ansible.builtin.template:
    src: config.kdl.j2
    dest: "{{ common_user_config_dir }}/zellij/config.kdl"
    mode: "0644"
    owner: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
