---
- name: Main PC setup
  hosts: my_machines
  gather_facts: true
  become: true

  roles:
    - role: apps
      tags: role_apps
    - role: fonts
      tags: role_fonts
    - role: bash
      tags: role_bash
    - role: wallpapers
      tags: role_wallpapers
    - role: i3
      when: ansible_distribution == "Linux Mint"
      tags: role_i3
    - role: sway
      when: ansible_distribution == "Linux Debian"
      tags: role_sway
    - role: editors
      tags: role_editors
    - role: golang
      tags: role_golang
