---
i3_user_name: "{{ user.name }}"
i3_user_group: "{{ user.group }}"
i3_user_home: "{{ user.home }}"
i3_user_email: "{{ user.email }}"
i3_user_passwd: "{{ user.passwd }}"

i3_config_dir: "{{ i3_user_home }}/.config/i3"

i3_config_font: JetBrains Mono 10

i3_config_wallpaper: "{{ i3_user_home }}/Pictures/guts_wallpaper.jpg"
